/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SolutionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/contact': typeof ContactRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/contact': typeof ContactRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/products': typeof ProductsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/contact': typeof ContactRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/approach'
    | '/contact'
    | '/products/$slug'
    | '/projects/$slug'
    | '/solutions/$slug'
    | '/products/'
    | '/projects/'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/approach'
    | '/contact'
    | '/products/$slug'
    | '/projects/$slug'
    | '/solutions/$slug'
    | '/products'
    | '/projects'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/approach'
    | '/contact'
    | '/products/$slug'
    | '/projects/$slug'
    | '/solutions/$slug'
    | '/products/'
    | '/projects/'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApproachRoute: typeof ApproachRoute
  ContactRoute: typeof ContactRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof SolutionsRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApproachRoute: ApproachRoute,
  ContactRoute: ContactRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
